### ISSUE TITLE
incorrect crop when height > width

### ISSUE THREAD

**Issue by mx1up** [personalizedrefrigerator/flutter_launcher_icons#3]
### :information_source: Info
Version: `6286e26`

### :speech_balloon: Description
trying out for https://github.com/fluttercommunity/flutter_launcher_icons/pull/155
I have an app icon with height bigger than width and it seems to crop off a slice at the top and bottom. Maybe this input image dimension is not supported but the android and ios target don't seem to suffer from this.
I guess there should be a check somewhere which side is the biggest and currently the smallest side is chosen.

### :scroll: Pubspec.yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  hive_generator: ^0.7.1
  flutter_launcher_icons:
    git:
      url: https://github.com/personalizedrefrigerator/flutter_launcher_icons

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "gfx/appicon.png"

**Comment by personalizedrefrigerator** [comment]
Oops! Sorry for the late reply! I had accidentally stopped watching this repository and have not been using flutter much recently!

This comment is to note that I have seen this issue and am working on fixing it!

**Comment by personalizedrefrigerator** [comment]
Thank you for the bug report! Please confirm that this is fixed!

**Comment by mx1up** [comment]
thanks, i will try it out

**Comment by mx1up** [comment]
sorry for the delay. in my project, it looks good to me now, thanks. I don't know if it was a bug in upstream or you fixed some other bugs, because there also seems to be a stretching bug fixed in the android icons (before the width got stretched, probably hadn't noticed before)
